// components/BatteryDisplay.vue
<script setup lang="ts">
import LightningIcon from '~icons/mdi/lightning-bolt';

const props = defineProps({
  isSupported: Boolean,
  charging: Boolean,
  level: {
    type: Number,
    default: 0,
  },
});

const battLevel = computed(() => props.level || 0);

const battColor = computed(() => {
  if (!props.isSupported || battLevel.value <= 0.1) {
    return 'bg-red-500';
  }

  if (battLevel.value <= 0.2) {
    return 'bg-yellow-500';
  }

  return 'bg-green-500';
});

const battPercentage = computed(() => (!props.isSupported ? 0 : Math.round(battLevel.value * 100)));
</script>

<template>
  <div class="flex items-center">
    <div class="flex-1 border-8 rounded-lg h-28 sm:h-32 bg-stone-700 border-stone-700">
      <div class="relative w-full h-full rounded-md bg-stone-600">
        <div :style="{ width: `${battPercentage}%` }" class="h-full rounded-md" :class="battColor"></div>

        <div class="absolute inset-0 flex items-center justify-center text-white">
          <LightningIcon v-if="props.charging" class="w-8 h-8" />
          <p class="text-2xl font-semibold">{{ battPercentage }}%</p>
        </div>
      </div>
    </div>

    <div class="w-6 rounded-r-lg h-7 sm:w-6 bg-stone-700"></div>
  </div>
</template>

// src/components/client/BatteryDisplay.tsx
import clsx from 'clsx'
import { HTMLProps } from 'react'
import { MdBolt } from 'react-icons/md'
import type { useBattery } from 'react-use'

type Props = {
  battery: ReturnType<typeof useBattery>
} & HTMLProps<HTMLDivElement>

const BatteryDisplay = ({ battery, className }: Props) => {
  const supported = battery.isSupported && battery.fetched

  const battPercentage = supported ? Math.round(battery.level * 100) : 0
  const battCharging = supported && battery.charging

  let battColor = 'bg-red-500'
  if (battPercentage > 10) {
    battColor = 'bg-yellow-500'
  } else if (battPercentage > 20) {
    battColor = 'bg-green-500'
  }

  return (
    <div className={clsx(['flex items-center', className])}>
      <div className="h-28 flex-1 rounded-lg border-8 border-stone-700 bg-stone-700 sm:h-32">
        <div className="relative h-full w-full rounded-md bg-stone-600">
          <div style={{ width: `${battPercentage}%` }} className={`h-full rounded-md ${battColor}`}></div>

          <div className="absolute inset-0 flex items-center justify-center text-white">
            {battCharging && <MdBolt className="h-8 w-8" />}
            <p className="text-2xl font-semibold">{battPercentage}%</p>
          </div>
        </div>
      </div>

      <div className="h-7 w-6 rounded-r-lg bg-stone-700 sm:w-6"></div>
    </div>
  )
}

export default BatteryDisplay
